services:
  # üîê KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      # CSP CORRETA PARA VITE (Keycloak 25)
      KC_HTTP_RESPONSE_HEADER__CONTENT_SECURITY_POLICY: "frame-ancestors 'self' http://localhost:3000;"

    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - hypesoft-net
    depends_on:
      - keycloak-db

  # üîê KEYCLOAK DB
  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - hypesoft-net

  # üçÉ MONGO
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - hypesoft-net

  # üß™ MONGO EXPRESS
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - hypesoft-net
    depends_on:
      - mongo

  # üñ•Ô∏è API (.NET 9) ‚Äì modo DEV com hot reload
  api:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ./backend:/src
    command: dotnet watch run --project src/Hypesoft.API/Hypesoft.API.csproj --urls "http://*:5000"
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Mongo: "mongodb://root:root@mongo:27017/hypesoft?authSource=admin"
      Keycloak__Authority: "http://keycloak:8080/realms/HypeSoftRealm"
      Keycloak__Audience: "hypesoft-backend"
    depends_on:
      - mongo
      - keycloak
    networks:
      - hypesoft-net

  # üåê FRONTEND (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5000"
        VITE_KEYCLOAK_URL: "http://localhost:8080"
        VITE_KEYCLOAK_REALM: "HypeSoftRealm"
        VITE_KEYCLOAK_CLIENT_ID: "frontend"
        VITE_REDIRECT_URL: "http://localhost:3000"
    ports:
      - "3000:80"
    depends_on:
    - api
    networks:
    - hypesoft-net


networks:
  hypesoft-net:
    driver: bridge

volumes:
  keycloak_db:
